version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - db
    ports:
      - '80:80'
  db:
    image: 'mariadb:10.4.7'
    ports:
      - '3306:3306'
    volumes:
      - './db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
