version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    networks:
      - frontend
    depends_on:
      - db
    ports:
      - '8080:80'
  db:
    image: mariadb:10.4.7
    networks:
      - backend
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
  frontend:
  backend:
